[package]
name = "runner"
version = "0.1.0"
edition = "2024"

[dependencies]
jwalk = "0.8.1"
ratatui = "0.29.0"
crossterm = "0.29.0"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
