[package]
name = "runa-tui"
description = "A fast, keyboard-focused terminal file manager (TUI). Highly configurable and lightweight."
version = "0.8.0"
edition = "2024"
rust-version = "1.90"
license = "MIT OR Apache-2.0"
repository = "https://github.com/alexm-dev/runa"
readme = "README.md"
authors = ["Alexandros McCray <alexandros.mc@proton.me>"]
categories = ["filesystem", "command-line-utilities", "command-line-interface"]
keywords = ["file-browser", "file-manager", "tui", "cli", "search"]

[[bin]]
name = "rn"
path = "src/main.rs"

[dependencies]
dirs = "6.0.0"
ratatui = "0.30.0"
crossterm = "0.29.0"
serde = { version = "1.0", features = ["derive"] }
toml = "1.0.3"
crossbeam-channel = "0.5.15"
unicode-width = "0.2.2"
humansize = "2.1.3"
chrono = "0.4.43"
fuzzy-matcher = "0.3.7"
which = "8.0.0"
ansi-to-tui = "8.0.1"
phf = { version = "0.13.1", features = ["macros"] }
trash = "5.2.5"

[dev-dependencies]
rand = "0.10.0"
tempfile = "3.24.0"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
debug = false

[profile.release-windows]
inherits = "release"
panic = "unwind"
